import Head from 'next/head'
import { Inter } from 'next/font/google'
import BookCatalog from '@/app/components/screens/bookCatalog/BookCatalog'
import withAuth from '@/app/components/auth/withAuth'

const inter = Inter({ subsets: ['latin'] })

function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				<BookCatalog />
			</main>
		</>
	)
}

export default withAuth(Home)
